sequenceDiagram
  actor UU as User
  participant DA as Desktop App
  participant DC as Desktop Controller
  participant MC as Mobile Controller
  participant MA as Mobile App

  note over UU, MA: Discovery
  UU->>DA: Request satellite profile
  DA->>DC: Identity request
  note over DC: Broadcast identity
  activate DC
  DC->>DA: Identity data
  DA->>UU: Display identity QR code
  UU->>MA: Scan QR code
  MA->>MC: Register satellite identity
  activate MC
  note over UU, MA: Handshake
  DC->>MC: Identity broadcast
  MC->>DC: Identity challenge
  DC->>MC: Identity response
  MC->>DC: Accept or reject
  deactivate DC
  note over UU, MA: Activity
  note over MA: UI blocked<br>to prevent<br>state conflicts
  activate MA
  loop
    par
      DA->>DC: Chat request
      DC->>MC: Satellite request
      note over MC: unwrap chat api, handle, and wrap
      MC->>MC: Apply relevant changes to local state
      MC->>DC: Satellite response
      DC->>DA: Chat response
    and
      MC->>DC: Satellite notification
      DC->>DA: Chat notification
    end
  end
  deactivate MA
  note over UU, MA: Restart
  activate DC
  DC->>MC: Identity broadcast
  MC->>DC: Identity challenge
  DC->>MC: Identity response
  alt
  MC->>DC: Accept
  note over MA, DA: Resume activity
  else
  MC->>DC: Reject
  note over MA, DA: Dispose session
  end

  note over UU, MA: Disposal
  alt Satellite-initiated
  UU->>DA: “Detach satellite”
  DA->>DC: Terminate session
  DC->>MC: Deregister identity
  else Host-initiated
  UU->>MA: “Detach satellite”
  MA->>MC: Deregister identity
  MC->>DC: Terminate session
  DC->>DA: Invalidate session state
  end
  note over DA,DC: Remove session data

  opt No sessions remaining
    note over MC: Stop listener
    deactivate MC
  end
