sequenceDiagram
  actor DU as Desktop
  participant DI as Desktop UI
  participant DC as Desktop Core
  participant MC as Mobile Core
  participant MI as Mobile UI
  actor MU as Mobile

  note over DU, MU: Discovery
  DU->>DI: Request satellite profile
  DI->>DC: Identity request
  note over DC: Broadcast identity
  activate DC
  DC->>DI: Identity data
  DI->>DU: Display identity QR code
  MU->>MI: Scan QR code
  MI->>MC: Register satellite identity
  activate MC
  note over DU, MU: Handshake
  DC->>MC: Identity broadcast
  MC->>DC: Identity challenge
  DC->>MC: Identity response
  opt First time handshake
    MC->>MI: Request confirmation
    MI->>MU: “Confirm sharing all the stuff with device XXX"”
    alt
      MU->>MI: “Accept”
      MI->>MC: Mark identity confirmed
      MC->>DC: Send confirmation
    else
      MU->>MI: “Reject”
      MI->>MC: Delete registered identity
      MC->>DC: Send cancellation
    end
  end
  deactivate DC
  note over DU, MU: Activity (only the main loop)
  note over MI: UI blocked<br>to prevent<br>state conflicts
  activate MI
  loop
    par
      DI->>DC: Chat request
      DC->>MC: Satellite request
      note over MC: unwrap chat api, handle, and wrap
      MC->>DC: Satellite response
      DC->>DI: Chat response
    and
      MC->>DC: Satellite notification
      DC->>DI: Chat notification
    end
  end
  deactivate MI
  note over DU, MU: Restart
  activate DC
  DC->>MC: Identity broadcast
  MC->>DC: Identity challenge
  DC->>MC: Identity response
  alt
    MC->>DC: Accept
    note over MI, DI: Resume activity
  else
    MC->>DC: Reject
    note over MI, DI: Dispose session
  end

  note over DU, MU: Disposal
  alt Satellite-initiated
  DU->>DI: “Detach satellite”
  DI->>DC: Terminate session
  DC->>MC: Deregister identity
  else Host-initiated
  MU->>MI: “Detach satellite”
  MI->>MC: Deregister identity
  MC->>DC: Terminate session
  DC->>DI: Invalidate session state
  end
  note over DI,DC: Remove session data

  opt No sessions remaining
    note over MC: Stop listener
    deactivate MC
  end
